id = "fern"
name = "Fern"
version = "0.1.0"
schema_version = 1
languages = ["languages/fern"]
authors = ["Niklas Heer <niklas.heer@gmail.com>"]
description = "Fern programming language support for Zed"
repository = "https://github.com/niklas-heer/fern"

[language_servers.fern-lsp]
name = "Fern LSP"
languages = ["Fern"]

[grammars.fern]
repository = "https://github.com/niklas-heer/fern"
rev = "6d4efbb2f14a73be872f7c8e94c5ac31e54afcb9"
path = "editor/tree-sitter-fern"
