id = "fern"
name = "Fern"
version = "0.1.0"
schema_version = 1
languages = ["languages/fern"]
authors = ["Niklas Heer <niklas.heer@gmail.com>"]
description = "Fern programming language support for Zed"
repository = "https://github.com/niklas-heer/fern"

[language_servers.fern-lsp]
name = "Fern LSP"
languages = ["Fern"]

[grammars.fern]
repository = "https://github.com/niklas-heer/fern"
rev = "354a677dfd497fbd86f90a581b04839b7a987899"
path = "editor/tree-sitter-fern"
