#!/usr/bin/env python3
"""Render Unicode16 Nd tables from the checksum-pinned, vendored primary UCD."""
import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "deps/unicode/16.0.0/DerivedGeneralCategory.txt"
SHA256 = "7676ab755a41ef82108460238569e60ad65c191ddafe61b36c6765ec1353f293"


def ranges(text):
    """Extract sorted scalar-only Nd ranges, rejecting corruption before rendering."""
    result = []
    for line in text.splitlines():
        body = line.split("#", 1)[0].strip()
        if not body:
            continue
        interval, category = map(str.strip, body.split(";"))
        if category != "Nd":
            continue
        endpoints = interval.split("..")
        if len(endpoints) not in (1, 2):
            raise ValueError("invalid Unicode interval")
        start, end = int(endpoints[0], 16), int(endpoints[-1], 16)
        if not 0 <= start <= end <= 0x10FFFF or (start <= 0xDFFF and end >= 0xD800):
            raise ValueError("invalid Unicode scalar range")
        if result and start <= result[-1][1]:
            raise ValueError("overlapping or unsorted Unicode ranges")
        result.append((start, end))
    if len(result) != 71 or sum(end - start + 1 for start, end in result) != 760:
        raise ValueError("unexpected Unicode16 Nd inventory")
    return result


def render(source=SOURCE):
    """Check the exact primary input and return deterministic C/Rust generated files."""
    with source.open("rb") as stream:
        data = stream.read(1024 * 1024 + 1)
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise ValueError("Unicode input checksum mismatch")
    values = ranges(data.decode("utf-8"))
    note = "Generated by scripts/generate_decimal_tables.py; do not edit. Unicode16 Nd, Unicode License V3: deps/unicode/LICENSE.txt."
    c = f"/* {note} */\nstatic const uint32_t decimal_ranges[][2] = {{\n"
    rust = f"// {note}\npub(super) const RANGES: &[(u32, u32)] = &[\n"
    for low, high in values:
        c += f"    {{0x{low:X}, 0x{high:X}}},\n"
        rust += f"    (0x{low:X}, 0x{high:X}),\n"
    return {ROOT / "runtime/fern_decimal_table.h": c + "};\n",
            ROOT / "compiler-rs/src/decimal_table.rs": rust + "];\n"}


def main():
    """Generate tables offline or report drift without changing tracked output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, text in render().items():
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f"generated decimal table differs: {path}")
        else:
            path.write_text(text)


if __name__ == "__main__":
    main()
