#!/usr/bin/env python3
"""Independent native output oracles for the shared QBE/Cranelift lowering."""
import argparse
import json
import os
import shlex
from pathlib import Path
import subprocess
import tempfile

from test_rust_collections import CASES as COLLECTIONS
from test_rust_types import CASES as TYPES

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "compiler-rs/tests"


def corpus():
    """Reuse authored expectations, never results generated by the other backend."""
    cases = {}
    for output in sorted(FIXTURES.rglob("*.stdout")):
        source = output.with_suffix(".fn")
        if source.is_file():
            stderr = output.with_suffix(".stderr")
            cases[source] = (1 if stderr.is_file() else 0, output.read_text(),
                             stderr.read_text() if stderr.is_file() else "")
    for group, expectations in [("collections", COLLECTIONS), ("types", TYPES)]:
        for name, stdout in expectations.items():
            cases[FIXTURES / group / f"{name}.fn"] = (0, stdout, "")
    for group in ["corpus", "json_values", "actors"]:
        manifest = json.loads((FIXTURES / group / "cases.json").read_text())
        entries = ([dict(case, file="valid/" + name + ".fn") for name, case in manifest["native"].items()]
                   if isinstance(manifest, dict) else manifest)
        for case in entries:
            cases[FIXTURES / group / case["file"]] = (
                case.get("exit", 0), case["stdout"], case.get("stderr", ""))
    missing = [str(source) for source in cases if not source.is_file()]
    assert not missing, missing
    return cases


def float_abi(directory, environment):
    """Exercise the fixed native Float boundary independently of either emitter."""
    flags = subprocess.run(["pkg-config", "--cflags", "--libs", "bdw-gc", "sqlite3", "openssl"],
                           env=environment, text=True, capture_output=True, check=True, timeout=10)
    binary = directory / "float-abi"
    subprocess.run([environment.get("CC", "cc"), "-std=c11", "-Wall", "-Wextra", "-Werror",
                    ROOT / "tests/fixtures/runtime_float_abi.c", ROOT / "bin/libfern_runtime.a",
                    *shlex.split(flags.stdout), "-pthread", "-lm", "-o", binary],
                   env=environment, capture_output=True, text=True, check=True, timeout=60)
    actual = subprocess.run([binary], env=environment, text=True, capture_output=True, timeout=10)
    assert (actual.returncode, actual.stdout, actual.stderr) == (0, "1.25-0\n", ""), actual


def main():
    """Build privately, require exact native outcomes, and fail before publishing any output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, default=ROOT / "compiler-rs/target/debug/fern-rs")
    parser.add_argument("--backend", choices=["qbe", "cranelift"], default="cranelift")
    args = parser.parse_args()
    compiler = args.compiler.resolve()
    environment = dict(os.environ)
    environment.pop("LIBRARY_PATH", None)
    environment["FERN_RUNTIME_LIB"] = str(ROOT / "bin/libfern_runtime.a")
    environment["FERN_QBE"] = str(ROOT / "bin/fern-qbe") if args.backend == "qbe" else "/missing-qbe-must-not-run"
    cases = corpus()
    with tempfile.TemporaryDirectory(prefix="fern-backend-corpus-") as temporary:
        directory = Path(temporary)
        float_abi(directory, environment)
        for index, (source, expected) in enumerate(cases.items(), 1):
            binary = directory / "program"
            built = subprocess.run([compiler, "build", source, f"--backend={args.backend}", "-o", binary],
                                   env=environment, cwd=directory, capture_output=True, text=True, timeout=60)
            if built.returncode:
                raise AssertionError((str(source.relative_to(ROOT)), "build", built.stderr))
            result = subprocess.run([binary], env=environment, cwd=directory,
                                    capture_output=True, text=True, timeout=30)
            actual = result.returncode, result.stdout, result.stderr
            if actual != expected:
                raise AssertionError((str(source.relative_to(ROOT)), actual, expected))
            if index % 25 == 0:
                print(f"{args.backend}: {index}/{len(cases)} native cases passed", flush=True)
    print(f"{args.backend}: {len(cases)} exact native output oracles passed")


if __name__ == "__main__":
    main()
