/**
 * AUTO-GENERATED by scripts/generate_editor_support.py from scripts/editor/grammar.js.in.
 * Edit the authored template and scanner.c; never edit this generated output.
 * Decision84: bounded editor syntax profile, verified against Rust source fixtures.
 */
module.exports = grammar({
  name: "fern",
  externals: $ => [$._newline, $._indent, $._dedent, $._top_level_fn, $._fn],
  extras: $ => [/[ \t]/, $.line_comment, $.block_comment],
  word: $ => $.identifier,
  conflicts: $ => [
    [$.type_variable, $.pattern],
    [$.type, $.constructor_pattern, $.expression],
    [$.generic_type, $.constructor_pattern, $.expression],
    [$.type_variable, $.pattern, $.expression],
    [$.constructor_pattern, $.expression],
    [$.generic_type, $.expression],
    [$.unit_type, $.tuple_pattern],
    [$.tuple_type],
    [$.unit_type, $.tuple_pattern, $.unit_literal],
    [$._body, $.binary_expression],
    [$.list_pattern, $.list_literal],
    [$.parameter, $.tuple_pattern],
    [$.tuple_pattern, $.unit_literal],
    [$.type, $.constructor_pattern],
    [$.qualified_type, $.expression],
    [$.parameter_list, $.unit_literal],
    [$.parameter_list, $.function_type],
    [$.pattern, $.expression],
    [$.unit_type, $.function_type],
    [$.type_group, $.function_type],
    [$.if_expression],
    [$.with_expression],
  ],
  rules: {
    source_file: $ => repeat(choice($._newline, $._declaration)),
    _declaration: $ => choice($.function_definition, $.type_alias,
      $.type_definition, $.newtype_definition, $.import_statement, $.attribute, $.let_binding),
    _statement: $ => choice($.let_binding, $.expression_statement, $.defer_statement, $.attribute),
    function_definition: $ => seq(optional("pub"), choice(alias($._fn, "fn"), alias($._top_level_fn, "fn")), field("name", alias($._declaration_name, $.identifier)),
      field("parameters", alias($._function_parameter_list, $.parameter_list)), optional(seq("if", field("guard", $.expression))),
      choice(seq(optional(seq("->", field("return_type", $.type))), ":", field("body", $._body)),
        seq("->", field("body", $._body)))),
    _function_parameter_list: $ => seq("(", optional(sep1(alias($._function_parameter, $.parameter), ",")), optional(","), ")"),
    _function_parameter: $ => seq(optional(seq(field("label", choice($.identifier, alias($.type_identifier, $.identifier))),
      token.immediate(/[ \t]+/))), field("pattern", $.pattern),
      optional(seq(":", field("type", $.type)))),
    parameter_list: $ => seq("(", optional(sep1($.parameter, ",")), optional(","), ")"),
    parameter: $ => seq(field("pattern", $.pattern), optional(seq(":", field("type", $.type)))),
    _body: $ => choice($.expression, $.block, $.defer_statement),
    block: $ => seq(repeat1($._newline), $._indent, repeat1(choice($._newline, $._statement)), $._dedent),
    expression_statement: $ => prec(-3, $.expression),
    let_binding: $ => seq("let", field("pattern", $.pattern), optional(seq(":", $.type)),
      "=", field("value", $.expression), optional(seq("else", ":", $._body))),
    import_statement: $ => seq("import", $.module_path, optional(seq("as", $.identifier))),
    attribute: $ => seq("@", $.identifier, choice($.string_literal, $.triple_string)),

    type_alias: $ => seq(optional("pub"), "type", field("name", $.type_identifier),
      optional($.type_parameters), "=", field("target", $.type)),
    newtype_definition: $ => seq(optional("pub"), "newtype", field("name", $.type_identifier),
      optional($.type_parameters), "=", field("constructor", $.type_identifier),
      "(", field("payload", $.type), ")"),
    type_parameters: $ => seq("(", sep1($.identifier, ","), optional(","), ")"),
    type_definition: $ => seq(optional("pub"), "type", field("name", $.type_identifier),
      optional($.type_parameters), ":", repeat1($._newline), $._indent,
      repeat1(choice($._newline, $.record_field, $.type_variant)), $._dedent),
    record_field: $ => seq(field("name", $.identifier), ":", field("type", $.type)),
    type_variant: $ => seq(field("name", $.type_identifier), optional($.variant_arguments)),
    variant_arguments: $ => seq("(", sep1(choice($.type, $.record_field), ","), optional(","), ")"),
    type: $ => choice($.type_identifier, $.type_variable, $.qualified_type, $.generic_type,
      $.unit_type, $.tuple_type, $.function_type, $.type_group, $.union_type),
    union_type: $ => prec.left(1, seq($.type, "|", $.type)),
    type_group: $ => seq("(", $.type, ")"),
    type_variable: $ => $.identifier,
    qualified_type: $ => seq(choice($.identifier, $.type_identifier), repeat1(seq(".", choice($.identifier, $.type_identifier)))),
    generic_type: $ => seq(choice($.type_identifier, $.qualified_type), $.type_arguments),
    type_arguments: $ => seq("(", sep1($.type, ","), optional(","), ")"),
    unit_type: $ => seq("(", ")"),
    tuple_type: $ => seq("(", $.type, ",", optional(sep1($.type, ",")), optional(","), ")"),
    function_type: $ => prec.right(seq(optional(alias($._fn, "fn")), "(", optional(sep1($.type, ",")),
      ")", "->", $.type)),

    pattern: $ => choice($.identifier, $.integer_literal, $.string_literal, $.boolean_literal,
      $.list_pattern, $.tuple_pattern, $.constructor_pattern),
    list_pattern: $ => seq("[", optional(sep1(choice($.pattern, $.rest_pattern), ",")), optional(","), "]"),
    tuple_pattern: $ => seq("(", optional(sep1(choice($.pattern, $.rest_pattern), ",")), optional(","), ")"),
    rest_pattern: $ => seq("..", $.identifier),
    constructor_pattern: $ => seq(choice($.type_identifier, $.qualified_type),
      optional(seq("(", optional(sep1($.pattern, ",")), optional(","), ")"))),

    expression: $ => choice($.identifier, alias($.type_identifier, $.identifier), $.integer_literal, $.float_literal, $.string_literal,
      $.triple_string, $.boolean_literal, $.unit_literal, $.list_literal, $.tuple_literal,
      $.parenthesized_expression, $.binary_expression, $.unary_expression, $.call_expression,
      $.member_access, $.question_expression, $.if_expression, $.match_expression,
      $.lambda_expression, $.return_statement, $.for_expression, $.range_expression,
      $.with_expression, $.map_literal, $.record_update, $.condition_match,
      $.postfix_if_expression, $.break_expression, $.continue_expression),
    unit_literal: $ => seq("(", ")"),
    list_literal: $ => seq("[", optional(sep1($.expression, ",")), optional(","), "]"),
    tuple_literal: $ => seq("(", $.expression, ",", optional(sep1($.expression, ",")), optional(","), ")"),
    parenthesized_expression: $ => seq("(", $.expression, ")"),
    argument_list: $ => seq("(", repeat($._newline), optional(seq(
      choice(seq($.expression, repeat(seq($._argument_separator, $.expression)),
          repeat(seq($._argument_separator, $.labeled_argument))),
        sep1($.labeled_argument, $._argument_separator)),
      optional(seq(repeat($._newline), ",")), repeat($._newline))), ")"),
    _argument_separator: $ => seq(repeat($._newline), ",", repeat($._newline)),
    labeled_argument: $ => seq(field("label", choice($.identifier, alias($.type_identifier, $.identifier))), ":", field("value", $.expression)),
    call_expression: $ => prec.left(14, seq(field("function", $.expression), field("arguments", $.argument_list))),
    member_access: $ => prec.left(15, seq(field("object", $.expression), ".",
      field("member", choice($.identifier, $.integer_literal)))),
    question_expression: $ => prec.left(16, seq($.expression, "?")),
    lambda_expression: $ => prec.right(seq(optional(alias($._fn, "fn")), $.parameter_list, "->", $._body)),
    unary_expression: $ => prec(12, seq(choice("-", "not", "~~~"), $.expression)),
    binary_expression: $ => choice(...[
      [0, "|>"], [0, "or"], [1, "and"], [3, "|||"], [4, "^^^"], [5, "&&&"],
      [6, choice("==", "!=")], [7, choice("<", "<=", ">", ">=")],
      [8, choice("<<<", ">>>")], [9, choice("+", "-")], [10, choice("*", "/", "%")],
      [11, "**"],
    ].map(([p, operator]) => (p === 11 ? prec.right : prec.left)(p,
      seq(field("left", $.expression), field("operator", operator), field("right", $.expression))))),
    if_expression: $ => seq("if", field("condition", $.expression), ":",
      field("consequence", $._body), optional(seq(repeat($._newline), "else", ":", field("alternative", $._body)))),
    match_expression: $ => seq("match", field("value", $.expression), ":", repeat1($._newline),
      $._indent, repeat1(choice($._newline, $.match_arm)), $._dedent),
    range_expression: $ => prec.left(2, seq(field("start", $.expression),
      field("operator", choice("..", "..=")), field("end", $.expression))),
    for_expression: $ => seq($._for_binding,
      field("iterable", $.expression), ":", field("body", $._body)),
    _for_binding: $ => seq("for", field("pattern", $.pattern), "in"),
    break_expression: $ => "break",
    continue_expression: $ => "continue",
    postfix_if_expression: $ => prec.left(-1, seq(field("value", $.expression),
      "if", field("condition", $.expression))),
    defer_statement: $ => prec.right(-2, seq("defer", field("value", $.expression))),
    condition_match: $ => seq("match", ":", repeat1($._newline), $._indent,
      repeat1(choice($._newline, $.condition_arm)), $._dedent),
    condition_arm: $ => seq(field("condition", $.expression), "->", field("body", $._body)),
    map_literal: $ => seq("%", "{", optional(sep1($.map_entry, ",")), optional(","), "}"),
    map_entry: $ => seq(field("key", $.expression), ":", field("value", $.expression)),
    record_update: $ => seq("%", "{", field("base", $.expression), "|",
      sep1($.update_field, ","), optional(","), "}"),
    update_field: $ => seq(field("name", $.identifier), ":", field("value", $.expression)),
    with_expression: $ => seq($._with_header,
      field("body", $._body), optional(seq(repeat($._newline), "else", $.with_handlers))),
    _with_header: $ => seq("with", $.with_bindings, repeat($._newline), "do"),
    with_bindings: $ => choice(sep1($.with_binding, ","),
      seq(repeat1($._newline), $._indent,
        repeat1(choice($._newline, seq($.with_binding, optional(",")))), $._dedent)),
    with_binding: $ => seq($._with_assignment, field("value", $.expression)),
    _with_assignment: $ => seq(field("pattern", $.pattern), "<-"),
    with_handlers: $ => choice($.match_arm, seq(repeat1($._newline), $._indent,
      repeat1(choice($._newline, $.match_arm)), $._dedent)),
    typed_pattern: $ => seq(field("pattern", $.pattern), ":", field("type", $.type)),
    match_arm: $ => seq(field("pattern", choice($.pattern, $.typed_pattern)), optional(seq("if", field("guard", $.expression))),
      "->", field("body", $._body)),
    return_statement: $ => prec.right(0, seq("return", $.expression)),
    // Keep declaration-name recovery contextual, as in the existing malformed corpus.
    _declaration_name: $ => /[A-Za-z_][A-Za-z0-9_]*/,
    identifier: $ => labelIdentifier(),
    type_identifier: $ => token(prec(1, /[A-Z][A-Za-z0-9_]*/)),
    module_path: $ => sep1($.identifier, "."),
    integer_literal: $ => /[0-9][0-9_]*/,
    float_literal: $ => /[0-9][0-9_]*\.[0-9][0-9_]*([eE][+-]?[0-9]+)?/,
    boolean_literal: $ => choice("true", "false"),
    string_literal: $ => seq('"', repeat(choice(/[^"\\\n{]+/, /\\./, $.string_interpolation)), '"'),
    string_interpolation: $ => seq("{", $.expression, "}"),
    triple_string: $ => token(/"""([^"]|"[^"]|""[^"])*"""/),
    line_comment: $ => token(seq("#", /[^\r\n]*/)),
    block_comment: $ => token(seq("/*", /[^*]*\*+([^/*][^*]*\*+)*/, "/")),
  },
});

// Keep comma-separated grammar sequences declarative and deterministic.
function sep1(rule, separator) {
  return seq(rule, repeat(seq(separator, rule)));
}

// ABI14 has no reserved-word sets. Exclude exact binding keywords from labels.
function labelIdentifier() {
  const words = "fn let if else true false and or not pub type match return for in while import with trait impl actor receive spawn where do defer as module break continue derive newtype send after".split(" ");
  const first = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_";
  const tail = first + "0123456789";
  const alternatives = [];
  function visit(prefix, remaining) {
    if (prefix && !remaining.includes("")) alternatives.push(prefix);
    const edges = [...new Set(remaining.filter(Boolean).map(word => word[0]))];
    const other = [...(prefix ? tail : first)].filter(c => !edges.includes(c));
    if (other.length) alternatives.push(prefix + "[" + other.join("") + "][A-Za-z0-9_]*");
    for (const edge of edges) {
      visit(prefix + edge, remaining.filter(word => word.startsWith(edge)).map(word => word.slice(1)));
    }
  }
  visit("", words);
  return new RegExp("(" + alternatives.join("|") + ")");
}
